### ISSUE TITLE
bug: broken links throughout! within a project, links don't work (have wrong address)

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/cwcom#20] opened 2016-12-12 12:39 UTC
I realized that on my phone AND on a laptop, when I'm in a project (say I've clicked on New Economic Policy) and I try to click on a text, the link address has changed (from what it was when I'm looking at all projects and clicking on a text) and it doesn't work. Can you change that?

![screen shot 2016-12-12 at 7 37 32 am](https://cloud.githubusercontent.com/assets/925548/21099746/fcad28ec-c03d-11e6-993d-a2e8fe245cd7.png)

![image 8](https://cloud.githubusercontent.com/assets/925548/21099752/01f747ec-c03e-11e6-915f-ce25954a59b5.png)

**Comment by orzubalsky** [comment] 2016-12-19 21:12
I think this is a duplicate of #17?

**Closed as completed by orzubalsky** 2016-12-19 21:12 UTC
